### ISSUE TITLE
Hydroponic basins's top side doesn't show plants.

### ISSUE THREAD

**Issue by Xerionus** [bbradson/Performance-Fish#40]
As in title, **plants** that are planted in **hydroponic basins** (and in similar things from other mods that work just like hydroponics) **are invisible** on the **top side**. They grow, can be harvested, can be highlighted, but are invisible.

https://gist.github.com/HugsLibRecordKeeper/1962d4b24fff8318092b85a839bc59b4

**Comment by bbradson** [comment]
Should be fixed now

**Comment by quicksilverfox** [comment]
It only fixed for basins that are placed horizontally. If placed vertically, it still does not work properly.
![image](https://github.com/bbradson/Performance-Fish/assets/28810140/2b3d1069-8873-4446-97f8-97f71f085320)

**Comment by bbradson** [comment]
Thanks. That should be fixed now too

**Comment by Cheremenin** [comment]
Getting this little visual glitch still
